name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ['debug', 'release']
      fail-fast: true

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
  
    - name: Gradle build ${{ matrix.type }} apk
      uses: eskatos/gradle-command-action@v1.3.3
      with:
        gradle-version: current
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        arguments: assemble${{ matrix.type }}
    
    - name: Sign release APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      if: matrix.type == 'release'

    - name: Upload release apk
      uses: actions/upload-artifact@master
      with:
        name: app-${{ matrix.type }}
        path: ${{ steps.sign_app.outputs.signedReleaseFile }}
      if: matrix.type == 'release'

    - name: Upload debug apk
      uses: actions/upload-artifact@master
      with:
        name: app-${{ matrix.type }}
        path: app/build/outputs/apk/${{ matrix.type }}/
      if: matrix.type == 'debug'

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    steps:
    - name: Download App Artifacts
      uses: actions/download-artifact@v3

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          app-debug/app-debug.apk
          app-release/app-release-unsigned-signed.apk
